### ISSUE TITLE
Create framework for legal, tech, social analysis of Pilot Group

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/platform-initiative#3]

**Comment by janetpkr** [comment]
@sarahpearson @peterspdx - can you take a look at the framework for analyzing the Pilot group, esp the legal/tos piece? doc here: https://docs.google.com/a/creativecommons.org/document/d/1gOp6coWJVZ58rmvrsTNFd920rgNvmkQ2RHhbuA-dr_o/edit?usp=sharing (for now only open to CC staff)

@mattl - can you take a look at the technical analysis framework and add anything you think is missing? 

We don't have to get it perfect, but we want to send them this as a draft by EOD tomorrow.

**Comment by sarahpearson** [comment]
@janeatcc I looked and just added one comment. Looks good to me. Thanks!

**Comment by mattl** [comment]
Asked some questions, tweaked some text.

**Comment by janetpkr** [comment]
Thanks - added some comments and questions back at ya

**Comment by janetpkr** [comment]
Thanks. Assigned to @peterspdx now for final review before sending on to WMF

**Comment by peterspdx** [comment]
I think it looks great.  Thanks, Jane!  The timeline, also, which you should go ahead and send.

**Comment by janetpkr** [comment]
@sarahpearson WMF made some additions/tweaks to legal framework, can you review when you get a chance? I resolved them all b/c I think it's good, but just in case. Thanks!

**Comment by sarahpearson** [comment]
@janeatcc I added some comments because I think the new additions are a little unclear, at least in terms of how they differ from what was already there. If too nitpicky, feel free to ignore. Fine otherwise, just feels like there is some redundancy there now.

**Comment by janetpkr** [comment]
@sarahpearson See comments plus resolved in doc. We realized that what was really missing was a high-level summary of TOS/legal of the platform, useful for framing what we view as important to fix as well, so we moved the categories up there. If all looks good, we can resolve this issue. Thanks!

**Comment by sarahpearson** [comment]
Looks great, thanks!

**Comment by janetpkr** [comment]
Jane needs to create templates for analysis now

**Comment by janetpkr** [comment]
@sarahpearson Here is the master document
