### ISSUE TITLE
review Imgur TOS

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/platform-initiative#46]
just a quick look to see if there's any issues with incorporating CC licenses: https://imgur.com/tos

maybe next week sometime? i'm talking to them Mon but can surface TOS later

**Comment by sarahpearson** [comment]
Just read them and added a bit to your doc. Ping me if you have questions!

**Comment by janetpkr** [comment]
Please re-review the NC clause (and anything else) and add specific rec to engagement doc: https://docs.google.com/a/creativecommons.org/document/d/1nX5sXeYJ49c_kHuoUvtsgTy4LNsISCPUOwPjplaQeqc/edit.

**Comment by janetpkr** [comment]
Hi Sarah - can you do this early next week? I am going to be checking in with Tim then...

**Comment by sarahpearson** [comment]
yes!
