### ISSUE TITLE
Comprehensive analysis for Pilot Group

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/platform-initiative#5]
on the legal, technical, and social barriers to CC license use and reuse (legal, marking/UI and tech analysis).

**Comment by janetpkr** [comment]
@sarahpearson Which legal analysis should we start with? Internet Archive, Flickr, or Vimeo? Given your sense of what is more urgent -- all three are top from my perspective. Can we get one done by next week?

**Comment by sarahpearson** [comment]
Sure. Let's start with IA since it affects The List app.

**Comment by sarahpearson** [comment]
Just finished analysis of IA. Should I close this issue, or is this intended to capture the entire project?

**Comment by janetpkr** [comment]
Entire project - leave open, thanks!

On Wed, Apr 1, 2015 at 10:01 AM, Sarah Pearson notifications@github.com
wrote:

> Just finished analysis of IA. Should I close this issue, or is this
> intended to capture the entire project?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativecommons/platform-initiative/issues/5#issuecomment-88547302
> .

## 

Jane Park
@janedaily
Creative Commons | Los Angeles

Make a donation to support CC in 2015: http://bit.ly/supportcc2015
