### ISSUE TITLE
Vimeo TOC

### ISSUE THREAD

**Issue by mattl** [creativecommons/platform-initiative#52]
> Certain types of content are not allowed on Vimeo.
> - No rips of movies, music, television, or any other third party copyrighted material.

I'd like to host an existing BY-ND video on Vimeo, but it's not mine.

**Comment by janetpkr** [comment]
Yep, we're aware of this. If you have a Vimeo Pro account you're allowed to if you have necessary rights and permissions: https://vimeo.com/help/guidelines.

This is part of our WMF analysis so it's in consideration. However, keep in mind that Vimeo wants itscreators uploading original, high quality content.

**Comment by mattl** [comment]
So in this instance it was uploading a video that's currently only available in Theora format elsewhere to Vimeo for wider views, etc. But yeah, glad to know it's on the radar.
