### ISSUE TITLE
Flickr's API TOS, Developer guide, and CC licenses

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/platform-initiative#53]
Matt,

1) Can a developer get CC license information on images from Flickr's API? Looks so https://www.flickr.com/services/api/flickr.photos.licenses.getInfo.html 

2) Do you think it is worth @sarahpearson's time to analyze Flickr's API TOS + Developer guidelines to see if any of it conflicts or pertains to CC licenses? 
https://www.flickr.com/services/api/tos/
https://www.flickr.com/services/developer/

3) Do you have any idea if https://code.flickr.net/ is kept up to date?

**Comment by sarahpearson** [comment]
@janeatcc For the WMF pilot, I limited my legal review to terms that bind normal users. I think we should stick with that for WMF analysis unless we previously agreed otherwise. Can always expand it later.

**Comment by janetpkr** [comment]
Sounds good @sarahpearson. I'm going to leave this issue up so @mattl can respond whether it's worth following up on these items separate from/following on WMF analysis.

**Comment by mattl** [comment]
1. Yep. You found it, though we could ask them to update that info for the newly added CC0/PD options.
2. Yes please. Flickr's API is seen as gold standard, so we should make sure there's no conflicts. @sarahpearson -- please do your legal magic.

**Comment by sarahpearson** [comment]
@janeatcc added two notes about the API terms to the WMF Pilot Group Analysis doc.

**Comment by janetpkr** [comment]
@sarahpearson I don't see any notes around Flickr, just Twitter and Vimeo?

**Comment by sarahpearson** [comment]
I promise they are there. In the WMF chart in the relevant categories. I'll highlight so you can see.
