### ISSUE TITLE
WP TOS

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/platform-initiative#55]
Review https://en.wordpress.com/tos/ eventually..

**Comment by sarahpearson** [comment]
Hey @janeatcc, can you define eventually? just wondering when to prioritize this.

**Comment by janetpkr** [comment]
@sarahpearson just off the phone with WP - in the next week would be good, but no rush if that's tight. definitely by the next staff call, just added milestone. Thank you!

Here's what we're looking for specifically:
- Is there anything in TOS that would conflict with licenses, with licensing user's own content under licenses or PD, with hosting third party content under other licenses/PD? (One use case to keep in mind is a plugin that would pull Commons content into a user's blog. Is it all clear for something like this to happen?)
- Are there best practices or enhancements we could recommend, beyond this? Can we make CC more prominent in the TOS somehow? eg. what is an ideal TOS that allows CC licensing own content and importing CC licensed content?
- Are there additional info pages, eg. in their support center, we could suggest that explicitly explain how to use CC on WP to complement the TOS?

**Comment by sarahpearson** [comment]
Great! Thanks @janeatcc!
