### ISSUE TITLE
MapStory TOS

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/platform-initiative#56]
MapStory has three main buckets of content:
1. Third party data from places like Open Street Map under various other open licenses, eg. ODDBL - aka Remote base map services
2. User contributed Story Layers, or data streams - any spatiotemporal data at any grain size - governed by default site license for data which is ODDBL
3. User media/stories built on top of these layers of data - defaulted currently at BY-SA 2.0 (but if they keep same license, we'd move them to 4.0)

What to look for (in addition to normal TOS review):
- ODDBL and BY-SA compatibility - yes? if not, needed?
- Could MapStory change its default terms for user-contributed data to CC0, considering its base layer pulling from sources that are ODDBL? End goal is just making it easier for data to work together cross-platforms, so viewing in this light, is this even desirable?
- BY-SA 4.0 for user contributed media -- is that the optimal license re their intent? or is there a better license/tool we should recommend (this goes beyond TOS, but just to keep in mind) 

Here's the TOS: http://wiki.mapstory.org/wiki/Terms_of_Service
Here's the licensing policy: http://wiki.mapstory.org/wiki/License_and_Copyright

We want to get some initial feedback to them by end of this month if possible. 
Here's [engagement doc](https://docs.google.com/document/d/1Vd37elPCo8B7WrKt99Ms956_bIH0m6XuZ6v_JkKjPUM/edit) with more background info (open to staff only).

**Comment by sarahpearson** [comment]
Wrote down some initial feedback. Will likely require follow up once we talk to them, but I'll close this issue for now and we can reopen as needed.
