### ISSUE TITLE
LinkedIn TOS

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/platform-initiative#57]
@sarahpearson could you please take an initial look at LinkedIn's terms by June 1? https://www.linkedin.com/legal/user-agreement. It's for LinkedIn, Pulse, and Slideshare. 

We'd want to think about publishing features that could incorporate CC, so anything affecting upload and offload of CC (user created and third party) content. Here's an example of a media rich post: https://www.linkedin.com/pulse/you-emotionally-intelligent-heres-how-know-sure-dr-travis-bradberry. Please add notes to [engagement doc](https://docs.google.com/document/d/1yCCCkQ-aPpH8ihlHXdZBHg_1BJdY6Gjbyg8AZ6aYScc/edit) (staff only).

Other pages that might be relevant (but less imp to get to before date noted):
- Community guidelines: https://help.linkedin.com/app/answers/detail/a_id/34593/
- Privacy policy: https://www.linkedin.com/legal/copyright-policy?trk=hb_ft_copy

**Comment by sarahpearson** [comment]
Added notes on User Agreement and Community Guidelines to engagement doc. Still need to review privacy policy.
