### ISSUE TITLE
Kindle TOS

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/platform-initiative#59]
@sarahpearson (another one) - possible to take a look by June 5? No worries if not (not imperative by this date) as I took a quick look and have a general idea of the big issues.

**Comment by janetpkr** [comment]
[Engagement doc](https://docs.google.com/document/d/15GvsOPGUfX9dFcr0izN9GOtgQ2S55_mW7cr_f3SbPTk/edit) - staff only.

**Comment by sarahpearson** [comment]
@janeatcc I read through the Direct Publishing TOS, the Kindle Store TOS, and the Amazon TOS. I put some comments and questions in the engagement doc and highlighted them in yellow so they are easy to find. Depending on what the plan is with them, we should talk at some point. Can give firmer recs if I have a better idea of what they are planning, etc.
