### ISSUE TITLE
Merlot TOS

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/platform-initiative#61]
Reviving Github-- woo!

Please review Merlot's policies: http://info.merlot.org/merlothelp/index.htm#policies_and_practices.htm

Specifically considering the following: 
- that it says CC BY 4.0 is default for user created bookmark collections and course e-portfolios
- that it allows for upload of third party CC licensed content
- that it accounts for upload of individual resources under all six of the CC licenses
- that it accounts for a new tool that will allow direct creation of resources on platform itself and publishing under CC licenses

**Comment by sarahpearson** [comment]
Notes and summary in the engagement doc. We should discuss.
