### ISSUE TITLE
edX TOS

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/platform-initiative#65]
Good news -- got someone to ferry suggestions. @sarahpearson can you review edX TOS? and coordinate with @peterspdx as I know she's done some work on this in the past. 

https://www.edx.org/edx-terms-service

Engagement doc is linked in master list.

Some background: They let institutions license entire courses + videos on their platform and under the full CC license suite. We are exploring add-ons to the integration in an upcoming hackathon that may enable additional licensing of specific files within a course like textbooks. Please also review for upload of third party content. 

cc: @cablegreen

**Comment by peterspdx** [comment]
Very happy to discuss once sarahpearson has made her initial review.

**Comment by sarahpearson** [comment]
I've reviewed. I've added my notes to engagement doc, which I'll send to @peterspdx.
