### ISSUE TITLE
Lumen TOS

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/platform-initiative#66]
Another for you! I don't think they have a full-on TOS but they have http://lumenlearning.com/copyright/ and some related attribution guidelines. If you could take a look and see if anything rings bells, that would be great.

Lumen has these types of content:
- very small amount of informational content owned by Lumen
- third party courses and materials owned by institutions, orgs, or faculty teams that Lumen works with to mark content and host on their candela back-end platform
- faculty contributed edits defaulted under cc by per separate agreements with schools they work with. edits are public but dont get put into canonical version of course until lumen approves

**Comment by sarahpearson** [comment]
I've reviewed. We can discuss later today.
