### ISSUE TITLE
Web integration wiki content gone

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/platform-initiative#68]
Content formerly on https://wiki.creativecommons.org/wiki/Web_Integration is gone? Know where I can find it?

**Comment by rheaplex** [comment]
I think we have someone maliciously deleting content on the Wiki. Investigating.

**Comment by rheaplex** [comment]
Yes this is back. It was deleted by a particularly vicious spammer and vandal. I've blocked them and reverted their changes. Thank you for reporting this.
