### ISSUE TITLE
EXIF metadata draft TBP on labs

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/platform-initiative#71]
@mattl and @robmyers, now that SOTC is largely over, do you think we can get a draft up on labs to start a leisurely discussion before xmas eve? We can allow folks to digest through the holiday and then dig in in January. What do you think?

**Comment by mattl** [comment]
maybe. We have not a lot of time left and a bunch of fundraising things to
do.

---

Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC

**Comment by janetpkr** [comment]
Ok, let's see where we are at the end of the week/early next. First iteration of platform model + toolkit should at least be done by Fri.

**Comment by janetpkr** [comment]
Think we can get a draft of this up by Monday for sharing? Doesn't have to be perfect (shouldn't be actually if we want engagement) but something to go back to platforms and WMF with to kick off the public conversation.
